export const CURRENT_TOURNAMENT = 'CURRENT_TOURNAMENT'
export const SAVE_TOURNAMENT = 'SAVE_TOURNAMENT'
export const SAVE_COMPETATION_FORMAT = 'SAVE_COMPETATION_FORMAT'
export const SET_TEMPLATE = 'SET_TEMPLATE'
export const SET_ALL_PITCHES = 'SET_ALL_PITCHES'
export const SET_PITCH_CAPACITY = 'SET_PITCH_CAPACITY'
export const SET_PITCH_ID = 'SET_PITCH_ID'
export const SET_PITCH_DATA = 'SET_PITCH_DATA'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
export const SET_VENUES = 'SET_VENUES'
export const SET_TEAMS = 'SET_TEAMS'
export const SET_TOURNAMENT_TOTAL_TIME = 'SET_TOURNAMENT_TOTAL_TIME'
export const SET_CURRENT_SCHEDULE_VIEW = 'SET_CURRENT_SCHEDULE_VIEW'
export const SET_CURRENT_SCHEDULE_VIEW_AGE_CATEGORY = 'SET_CURRENT_SCHEDULE_VIEW_AGE_CATEGORY'
export const SET_CURRENT_AGE_CATEGORY_ID = 'SET_CURRENT_AGE_CATEGORY_ID'
export const SET_SCORE_AUTO_UPDATE = 'SET_SCORE_AUTO_UPDATE'



export const SET_TOURNAMENT_STATUS = 'SET_TOURNAMENT_FIELD'
export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const SET_TOURNAMENT_FILTER = 'SET_TOURNAMENT_FILTER'
export const TOTAL_MATCHES = 'TOTAL_MATCHES'
export const TOTAL_REFEREES = 'TOTAL_REFEREES'
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW'
export const IS_ADMIN = 'IS_ADMIN'
export const SET_REFEREES = 'SET_REFEREES'
export const SET_STAGE_VIEW = 'SET_STAGE_VIEW'
export const SET_STAGES = 'SET_STAGES'
export const COMPETITION_LIST = 'COMPETITION_LIST'
export const SET_MATCHES = 'SET_MATCHES'
export const SET_COMPETITION_WITH_GAMES = 'SET_COMPETITION_WITH_GAMES'
export const TOURNAMENT_STAGES = 'TOURNAMENT_STAGES'
export const SET_SCHEDULED_MATCHES = 'SET_SCHEDULED_MATCHES'
export const SET_PITCH_PLANNER_IN_ENLARGE_MODE = 'SET_PITCH_PLANNER_IN_ENLARGE_MODE'
export const RESET_PITCH_PLANNER_FROM_ENLARGE_MODE = 'RESET_PITCH_PLANNER_FROM_ENLARGE_MODE'
export const SET_PRINT_PITCH_PLANNER = 'SET_PRINT_PITCH_PLANNER'
export const RESET_PRINT_PITCH_PLANNER = 'RESET_PRINT_PITCH_PLANNER'
export const SET_UNSAVEMATCH_DATA = 'SET_UNSAVEMATCH_DATA'
export const SET_UNSAVEMATCH_STATUS = 'SET_UNSAVEMATCH_STATUS'

// Image path
export const SET_IMAGE_PATH = 'SET_IMAGE_PATH';
export const SET_MAP_KEY = 'SET_MAP_KEY';
export const SET_MATCH_IDLETIME = 'SET_MATCH_IDLETIME';

// Website Mutations
export const CURRENT_WEBSITE = 'CURRENT_WEBSITE';
export const WEBSITE_DATA = 'WEBSITE_DATA';
export const RESET_WEBSITE_DETAIL = 'RESET_WEBSITE_DETAIL';
export const SET_PREVIEW_DETAIL = 'SET_PREVIEW_DETAIL';

// Current layout
export const SET_CURRENT_LAYOUT = 'SET_CURRENT_LAYOUT';

// Presentation
export const SET_SCREEN_ROTATE_TIME = 'SET_SCREEN_ROTATE_TIME';

export const SET_SHOW_BASIC_TOURNAMENT_FORMAT = 'SET_SHOW_BASIC_TOURNAMENT_FORMAT';