# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESR

  target 'ESRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ESRUITests' do
    inherit! :search_paths
    # Pods for testing
  end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
pod 'AFNetworking', '~> 2.5'
pod 'Fabric'
pod 'Crashlytics'
pod "MBCircularProgressBar"
pod 'SVProgressHUD'
pod 'Fabric'
pod 'Crashlytics'
use_frameworks!
end
