# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # For custom Tabbar
  pod "ESTabBarController-swift"
  
  # Craslytics
  pod 'Fabric'
  pod 'Crashlytics', '3.10'

  # For API calling
  pod 'Alamofire', '~> 4.7'

  # For image loading
  pod 'SDWebImage', '~> 4.0'
end
